import { writeFileSync } from "fs";
import { join } from "path";
import type { Prompt } from "./library.js";

export function syncCursorRules(prompts: Prompt[], outPath: string) {
  const lines = prompts
    .filter((p) => !p.destination || p.destination === ".cursorrules")
    .map((p) => `## ${p.title}\n\n${p.content}`)
    .join("\n\n---\n\n");

  writeFileSync(outPath, `# Auto-generated by claude-prompts\n\n${lines}\n`);
}

export function syncAgentsMd(prompts: Prompt[], outPath: string) {
  const lines = prompts
    .filter((p) => !p.destination || p.destination === "AGENTS.md")
    .map((p) => `### ${p.title}\n\n${p.content}`)
    .join("\n\n---\n\n");

  writeFileSync(outPath, `# Auto-generated by claude-prompts\n\n${lines}\n`);
}

export function syncAll(prompts: Prompt[], targets: string[], cwd: string) {
  for (const target of targets) {
    const outPath = join(cwd, target);
    if (target === ".cursorrules") {
      syncCursorRules(prompts, outPath);
      console.log(`Synced ${prompts.length} prompt(s) to ${target}`);
    } else if (target === "AGENTS.md") {
      syncAgentsMd(prompts, outPath);
      console.log(`Synced ${prompts.length} prompt(s) to ${target}`);
    } else {
      console.warn(`Unknown sync target: ${target}`);
    }
  }
}
